## Assignment 1

(a)  How many nodes and edges are there in the networks?

In [3]:
import networkx as nx

# Path to the Facebook-Ego dataset files
facebook_edges_file = 'datasets/1684.edges'

# Load the Facebook ego network
facebook_ego_graph = nx.read_edgelist(facebook_edges_file)

# Get number of nodes and edges
num_nodes_facebook = facebook_ego_graph.number_of_nodes()
num_edges_facebook = facebook_ego_graph.number_of_edges()

print(f"Facebook-Ego Network: {num_nodes_facebook} nodes, {num_edges_facebook} edges")


Facebook-Ego Network: 157 nodes, 569 edges


In [4]:
# Path to the Twitter-Ego dataset files
twitter_edges_file = 'datasets/2029971.edges'

# Load the Twitter ego network (directed)
twitter_ego_graph = nx.read_edgelist(twitter_edges_file, create_using=nx.DiGraph())

# Get number of nodes and edges
num_nodes_twitter = twitter_ego_graph.number_of_nodes()
num_edges_twitter = twitter_ego_graph.number_of_edges()

print(f"Twitter-Ego Network: {num_nodes_twitter} nodes, {num_edges_twitter} edges")


Twitter-Ego Network: 143 nodes, 2830 edges


(b) What are the maximum degree and the average degree of the networks?

In [8]:
# Calculate maximum degree and average degree for Facebook-Ego
degrees_facebook = [degree for node, degree in facebook_ego_graph.degree()]
max_degree_facebook = max(degrees_facebook)
avg_degree_facebook = sum(degrees_facebook) / num_nodes_facebook

print(f"Facebook-Ego Network: Maximum Degree = {max_degree_facebook}, Average Degree = {avg_degree_facebook:.2f}")


Facebook-Ego Network: Maximum Degree = 30, Average Degree = 7.25


In [6]:
# Calculate maximum degree and average degree for Twitter-Ego
degrees_twitter = [degree for node, degree in twitter_ego_graph.degree()]
max_degree_twitter = max(degrees_twitter)
avg_degree_twitter = sum(degrees_twitter) / num_nodes_twitter

print(f"Twitter-Ego Network: Maximum Degree = {max_degree_twitter}, Average Degree = {avg_degree_twitter:.2f}")


Twitter-Ego Network: Maximum Degree = 142, Average Degree = 39.58


(c) Extract 5 - 8 nodes from the network and state them as a partial network. What is the adjacency
matrix of the partial network? Why do we need adjacency matrix to describe the structure of
the network?

In [11]:
import random
import numpy as np

# Function to extract a partial network and its adjacency matrix
def extract_partial_network(graph, num_nodes):
    # Randomly select nodes
    selected_nodes = random.sample(graph.nodes(), num_nodes)
    subgraph = graph.subgraph(selected_nodes)

    # Get the adjacency matrix
    adjacency_matrix = nx.to_numpy_array(subgraph)

    return selected_nodes, adjacency_matrix

# Extract partial network from Facebook-Ego
facebook_partial_nodes, facebook_adjacency_matrix = extract_partial_network(facebook_ego_graph, 6)
print(f"Facebook-Ego Partial Network Nodes: {facebook_partial_nodes}")
print("Adjacency Matrix:")
print(facebook_adjacency_matrix)

# Extract partial network from Twitter-Ego
twitter_partial_nodes, twitter_adjacency_matrix = extract_partial_network(twitter_ego_graph, 6)
print(f"Twitter-Ego Partial Network Nodes: {twitter_partial_nodes}")
print("Adjacency Matrix:")
print(twitter_adjacency_matrix)


Facebook-Ego Partial Network Nodes: ['2782', '2791', '2789', '2690', '2793', '2676']
Adjacency Matrix:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Twitter-Ego Partial Network Nodes: ['29114279', '20838196', '14292370', '34560904', '16436311', '15855519']
Adjacency Matrix:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]


C:\Users\dency\AppData\Local\Temp\ipykernel_24360\1852005056.py:7: DeprecationWarning: Sampling from a set deprecated
since Python 3.9 and will be removed in a subsequent version.
  selected_nodes = random.sample(graph.nodes(), num_nodes)


The adjacency matrix is a powerful representation of a graph. It provides a concise way to represent the graph's structure. Each cell in the matrix indicates whether a pair of nodes is connected.